// src/data/courses-dil.js

export const courses = [
  {
    slug: "a1-seviyesi-ingilizce",
    title: "A1 Seviyesi İngilizce (A1-1 / A1-2) Temel Seviye",
    category: "Dil Eğitimi",
    breadcrumb: "Dil Eğitimi > İngilizce > A1 Temel",
    image: "/images/ingilizce.jpg",
    instructors: [
      {
        slug: "baris-akcay",
        name: "Barış Akçay",
        since: 2015,
        rating: 4.7,
        privatePrice: 1200,
        groupPrice: 600,
        corporate: true,
        online: true,
        location: "İstanbul Anadolu Yakası",
        bio: "10 yıllık İngilizce öğretmeni, A1-A2 seviyelerinde uzman.",
        specialties: ["A1-1", "A1-2", "A2-1"]
      },
      {
        slug: "sevilay-ergin",
        name: "Sevilay Ergin",
        since: 2018,
        rating: 4.5,
        privatePrice: 1100,
        groupPrice: 550,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "Başlangıç seviyesinde uzman, çocuklara ve yetişkinlere ders.",
        specialties: ["A1-1", "A1-2"]
      },
      {
        slug: "cemalettin-kaya",
        name: "Cemalettin Kaya",
        since: 2014,
        rating: 4.8,
        privatePrice: 1300,
        groupPrice: 650,
        corporate: true,
        online: true,
        location: "Bursa",
        bio: "15 yıllık deneyim, konuşma pratiği ve temel seviye uzmanı.",
        specialties: ["A1-1", "A1-2", "A2-1", "A2-2", "Konuşma Pratiği"]
      },
      {
        slug: "neslihan-bayrak",
        name: "Neslihan Bayrak",
        since: 2017,
        rating: 4.6,
        privatePrice: 1150,
        groupPrice: 575,
        corporate: false,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "Gençlere ve yetişkinlere A1 seviyesinde dersler.",
        specialties: ["A1-1", "A1-2", "A2-1"]
      },
      {
        slug: "ilker-gunay",
        name: "İlker Günay",
        since: 2019,
        rating: 4.4,
        privatePrice: 1000,
        groupPrice: 500,
        corporate: false,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "Temel seviye uzmanı, sabırlı ve anlaşılır anlatım.",
        specialties: ["A1-1", "A1-2"]
      },
      {
        slug: "feride-gunes",
        name: "Feride Güneş",
        since: 2016,
        rating: 4.7,
        privatePrice: 1250,
        groupPrice: 625,
        corporate: true,
        online: true,
        location: "Kocaeli",
        bio: "Kocaeli'de A1 ve A2 seviyelerinde eğitmen.",
        specialties: ["A1-1", "A1-2", "A2-1", "A2-2"]
      },
      {
        slug: "berrin-yuksel",
        name: "Berrin Yüksel",
        since: 2013,
        rating: 4.9,
        privatePrice: 1400,
        groupPrice: 700,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "Uzun yıllardır A1 ve A2 seviyelerinde eğitmen.",
        specialties: ["A1-1", "A1-2", "A2-1", "A2-2", "Konuşma Pratiği"]
      },
      {
        slug: "belma-karaca",
        name: "Belma Karaca",
        since: 2016,
        rating: 4.7,
        privatePrice: 1250,
        groupPrice: 625,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "A1, B1 ve konuşma pratiği dersleri.",
        specialties: ["A1-1", "A1-2", "B1-1", "Konuşma Pratiği"]
      },
      {
        slug: "ercan-toprak",
        name: "Ercan Toprak",
        since: 2018,
        rating: 4.5,
        privatePrice: 1100,
        groupPrice: 550,
        corporate: false,
        online: true,
        location: "İzmir",
        bio: "İzmir'de yaşayan, A1-A2 ve konuşma pratiği dersleri.",
        specialties: ["A1-1", "A1-2", "A2-1", "Konuşma Pratiği"]
      },
      {
        slug: "pembe-karadeniz",
        name: "Pembe Karadeniz",
        since: 2017,
        rating: 4.6,
        privatePrice: 1200,
        groupPrice: 600,
        corporate: true,
        online: true,
        location: "Bursa",
        bio: "Bursa'da A1 ve B1 seviyelerinde dersler.",
        specialties: ["A1-1", "A1-2", "B1-1"]
      },
      
      {
        slug: "teoman-ilhan",
        name: "Teoman İlhan",
        since: 2015,
        rating: 4.6,
        privatePrice: 1200,
        groupPrice: 600,
        corporate: false,
        online: true,
        location: "Konya",
        bio: "Konya'da A1 ve B1 seviyelerinde ders veriyor.",
        specialties: ["A1-1", "A1-2", "B1-1", "B1-2"]
      }
    ],
    description: "A1 seviyesi İngilizce, temel dil bilgisi ve günlük konuşma becerilerini kapsar. Bu kursta A1-1 ve A1-2 alt seviyeleri işlenir.",
    whyTake: "İngilizceye sıfırdan başlamak ve sağlam bir temel oluşturmak için idealdir.",
    employmentAreas: "Temel İngilizce gerektiren işler, seyahat, günlük iletişim.",
    requirements: "Hiçbir ön koşul yoktur."
  },
  {
    slug: "a2-seviyesi-ingilizce",
    title: "A2 Seviyesi İngilizce (A2-1 / A2-2) Temel Seviye",
    category: "Dil Eğitimi",
    breadcrumb: "Dil Eğitimi > İngilizce > A2 Temel",
    image: "/images/ingilizce.jpg",
    instructors: [
      {
        slug: "asuman-guler",
        name: "Asuman Güler",
        since: 2015,
        rating: 4.7,
        privatePrice: 1600,
        groupPrice: 800,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "A2 ve B1 seviyelerinde uzman, konuşma ağırlıklı dersler.",
        specialties: ["A2-1", "A2-2", "B1-1", "B1-2"]
      },
      {
        slug: "cemalettin-kaya",
        name: "Cemalettin Kaya",
        since: 2014,
        rating: 4.8,
        privatePrice: 1700,
        groupPrice: 850,
        corporate: true,
        online: true,
        location: "İstanbul Anadolu Yakası",
        bio: "A2 ve konuşma pratiğinde deneyimli.",
        specialties: ["A1-1", "A1-2", "A2-1", "A2-2", "Konuşma Pratiği"]
      },
      {
        slug: "fikret-doruk",
        name: "Fikret Doruk",
        since: 2016,
        rating: 4.6,
        privatePrice: 1550,
        groupPrice: 775,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "A2 ve B1 seviyelerinde ders veriyor.",
        specialties: ["A2-1", "A2-2", "B1-1", "B1-2"]
      },
      {
        slug: "berrin-yuksel",
        name: "Berrin Yüksel",
        since: 2013,
        rating: 4.9,
        privatePrice: 1800,
        groupPrice: 900,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "A2 seviyesinde uzun yıllar deneyim.",
        specialties: ["A1-1", "A1-2", "A2-1", "A2-2", "Konuşma Pratiği"]
      },
      {
        slug: "perihan-akman",
        name: "Perihan Akman",
        since: 2017,
        rating: 4.5,
        privatePrice: 1500,
        groupPrice: 750,
        corporate: false,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "A2 ve B1 seviyelerinde dersler.",
        specialties: ["A2-1", "A2-2", "B1-1"]
      },
      {
        slug: "timur-yalaz",
        name: "Timur Yalaz",
        since: 2014,
        rating: 4.8,
        privatePrice: 1750,
        groupPrice: 875,
        corporate: true,
        online: true,
        location: "Ankara",
        bio: "Ankara'da A2, B1, B2 seviyelerinde eğitmen.",
        specialties: ["A2-1", "A2-2", "B1-1", "B1-2", "B2-1"]
      },
      {
        slug: "ercan-toprak",
        name: "Ercan Toprak",
        since: 2018,
        rating: 4.5,
        privatePrice: 1500,
        groupPrice: 750,
        corporate: false,
        online: true,
        location: "İzmir",
        bio: "İzmir'de A2 ve konuşma pratiği dersleri.",
        specialties: ["A1-1", "A1-2", "A2-1", "Konuşma Pratiği"]
      },
      {
        slug: "nejat-durmaz",
        name: "Nejat Durmaz",
        since: 2016,
        rating: 4.6,
        privatePrice: 1600,
        groupPrice: 800,
        corporate: true,
        online: true,
        location: "Antalya",
        bio: "Antalya'da A2 ve B1 seviyelerinde ders veriyor.",
        specialties: ["A2-1", "A2-2", "B1-1", "B1-2"]
      },
      {
        slug: "feride-gunes",
        name: "Feride Güneş",
        since: 2016,
        rating: 4.7,
        privatePrice: 1650,
        groupPrice: 825,
        corporate: true,
        online: true,
        location: "Kocaeli",
        bio: "Kocaeli'de A2 seviyesinde dersler.",
        specialties: ["A1-1", "A1-2", "A2-1", "A2-2"]
      }
    ],
    description: "A2 seviyesi İngilizce, temel dil bilgisini pekiştirir ve basit cümlelerle iletişim kurmayı sağlar. A2-1 ve A2-2 alt seviyelerini kapsar.",
    whyTake: "A1 seviyesini tamamlayanlar için bir sonraki adım.",
    employmentAreas: "Turizm, müşteri hizmetleri, temel iş İngilizcesi.",
    requirements: "A1 seviyesini tamamlamış olmak."
  },
  {
    slug: "b1-seviyesi-ingilizce",
    title: "B1 Seviyesi İngilizce (B1-1 / B1-2) Orta Seviye",
    category: "Dil Eğitimi",
    breadcrumb: "Dil Eğitimi > İngilizce > B1 Orta",
    image: "/images/ingilizce.jpg",
    instructors: [
      {
        slug: "duygu-ozer",
        name: "Duygu Özer",
        since: 2014,
        rating: 4.8,
        privatePrice: 2200,
        groupPrice: 1100,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "B1, B2 ve konuşma pratiğinde uzman.",
        specialties: ["B1-1", "B1-2", "B2-1", "Konuşma Pratiği"]
      },
      {
        slug: "asuman-guler",
        name: "Asuman Güler",
        since: 2015,
        rating: 4.7,
        privatePrice: 2100,
        groupPrice: 1050,
        corporate: true,
        online: true,
        location: "İstanbul Anadolu Yakası",
        bio: "B1 ve A2 seviyelerinde deneyimli.",
        specialties: ["A2-1", "A2-2", "B1-1", "B1-2"]
      },
      {
        slug: "ozge-altan",
        name: "Özge Altan",
        since: 2016,
        rating: 4.7,
        privatePrice: 2150,
        groupPrice: 1075,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "B1 ve B2 seviyelerinde ders veriyor.",
        specialties: ["B1-1", "B1-2", "B2-1", "B2-2"]
      },
      {
        slug: "fikret-doruk",
        name: "Fikret Doruk",
        since: 2016,
        rating: 4.6,
        privatePrice: 2050,
        groupPrice: 1025,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "B1 ve A2 seviyelerinde eğitmen.",
        specialties: ["A2-1", "A2-2", "B1-1", "B1-2"]
      },
      {
        slug: "atilla-ozcan",
        name: "Atilla Özcan",
        since: 2013,
        rating: 4.9,
        privatePrice: 2300,
        groupPrice: 1150,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "B1, B2, C1 seviyelerinde uzman.",
        specialties: ["B1-1", "B1-2", "B2-1", "B2-2", "C1-1"]
      },
      {
        slug: "cuneyt-ertugrul",
        name: "Cüneyt Ertuğrul",
        since: 2015,
        rating: 4.6,
        privatePrice: 2100,
        groupPrice: 1050,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "B1, C1 ve konuşma pratiği dersleri.",
        specialties: ["B1-1", "B1-2", "C1-1", "Konuşma Pratiği"]
      },
      {
        slug: "belma-karaca",
        name: "Belma Karaca",
        since: 2016,
        rating: 4.7,
        privatePrice: 2150,
        groupPrice: 1075,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "B1 ve konuşma pratiği dersleri.",
        specialties: ["A1-1", "A1-2", "B1-1", "Konuşma Pratiği"]
      },
      {
        slug: "timur-yalaz",
        name: "Timur Yalaz",
        since: 2014,
        rating: 4.8,
        privatePrice: 2250,
        groupPrice: 1125,
        corporate: true,
        online: true,
        location: "Ankara",
        bio: "Ankara'da B1, B2 ve A2 seviyeleri.",
        specialties: ["A2-1", "A2-2", "B1-1", "B1-2", "B2-1"]
      },
      {
        slug: "pembe-karadeniz",
        name: "Pembe Karadeniz",
        since: 2017,
        rating: 4.6,
        privatePrice: 2100,
        groupPrice: 1050,
        corporate: true,
        online: true,
        location: "Bursa",
        bio: "Bursa'da B1 ve A1 seviyelerinde ders.",
        specialties: ["A1-1", "A1-2", "B1-1"]
      },
      {
        slug: "gurkan-sahbaz",
        name: "Gürkan Şahbaz",
        since: 2015,
        rating: 4.7,
        privatePrice: 2200,
        groupPrice: 1100,
        corporate: true,
        online: true,
        location: "Bursa",
        bio: "B1, B2 ve konuşma pratiği dersleri.",
        specialties: ["B1-1", "B1-2", "B2-1", "B2-2", "Konuşma Pratiği"]
      },
      {
        slug: "nejat-durmaz",
        name: "Nejat Durmaz",
        since: 2016,
        rating: 4.6,
        privatePrice: 2150,
        groupPrice: 1075,
        corporate: true,
        online: true,
        location: "Antalya",
        bio: "Antalya'da B1 ve A2 seviyeleri.",
        specialties: ["A2-1", "A2-2", "B1-1", "B1-2"]
      },
      {
        slug: "cigdem-berksoy",
        name: "Çiğdem Berksoy",
        since: 2017,
        rating: 4.7,
        privatePrice: 2200,
        groupPrice: 1100,
        corporate: true,
        online: true,
        location: "Eskişehir",
        bio: "Eskişehir'de B1, B2 ve konuşma pratiği.",
        specialties: ["B1-1", "B1-2", "B2-1", "Konuşma Pratiği"]
      },
      {
        slug: "teoman-ilhan",
        name: "Teoman İlhan",
        since: 2015,
        rating: 4.6,
        privatePrice: 2100,
        groupPrice: 1050,
        corporate: false,
        online: true,
        location: "Konya",
        bio: "Konya'da B1 ve A1 seviyeleri.",
        specialties: ["A1-1", "A1-2", "B1-1", "B1-2"]
      },
      {
        slug: "reyhan-yildirim",
        name: "Reyhan Yıldırım",
        since: 2014,
        rating: 4.9,
        privatePrice: 2400,
        groupPrice: 1200,
        corporate: true,
        online: true,
        location: "Gaziantep",
        bio: "Gaziantep'te B1, B2, C1 ve konuşma pratiği.",
        specialties: ["B1-1", "B1-2", "B2-1", "B2-2", "C1-1", "Konuşma Pratiği"]
      }
    ],
    description: "B1 seviyesi İngilizce, orta seviyede dil bilgisi ve günlük konuşma becerilerini geliştirir. B1-1 ve B1-2 alt seviyelerini kapsar.",
    whyTake: "İngilizceyi akıcı bir şekilde konuşmaya başlamak için.",
    employmentAreas: "Müşteri temsilciliği, satış, yurt dışı eğitim.",
    requirements: "A2 seviyesini tamamlamış olmak."
  },
  {
    slug: "b2-seviyesi-ingilizce",
    title: "B2 Seviyesi İngilizce (B2-1 / B2-2) Orta-İleri Seviye",
    category: "Dil Eğitimi",
    breadcrumb: "Dil Eğitimi > İngilizce > B2 Orta-İleri",
    image: "/images/ingilizce.jpg",
    instructors: [
      {
        slug: "duygu-ozer",
        name: "Duygu Özer",
        since: 2014,
        rating: 4.8,
        privatePrice: 2800,
        groupPrice: 1400,
        corporate: true,
        online: true,
        location: "İstanbul Anadolu Yakası",
        bio: "B2 ve konuşma pratiğinde uzman.",
        specialties: ["B1-1", "B1-2", "B2-1", "Konuşma Pratiği"]
      },
      {
        slug: "taner-simsek",
        name: "Taner Şimşek",
        since: 2013,
        rating: 4.9,
        privatePrice: 3000,
        groupPrice: 1500,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "B2, C1 ve konuşma pratiği dersleri.",
        specialties: ["B2-1", "B2-2", "C1-1", "Konuşma Pratiği"]
      },
      {
        slug: "ozge-altan",
        name: "Özge Altan",
        since: 2016,
        rating: 4.7,
        privatePrice: 2700,
        groupPrice: 1350,
        corporate: true,
        online: true,
        location: "İstanbul Anadolu Yakası",
        bio: "B2 ve B1 seviyelerinde eğitmen.",
        specialties: ["B1-1", "B1-2", "B2-1", "B2-2"]
      },
      {
        slug: "hande-bilgin",
        name: "Hande Bilgin",
        since: 2015,
        rating: 4.8,
        privatePrice: 2900,
        groupPrice: 1450,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "B2, C1 ve konuşma pratiği dersleri.",
        specialties: ["B2-1", "B2-2", "C1-1", "C1-2", "Konuşma Pratiği"]
      },
      {
        slug: "atilla-ozcan",
        name: "Atilla Özcan",
        since: 2013,
        rating: 4.9,
        privatePrice: 3000,
        groupPrice: 1500,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "B2, C1 ve B1 seviyeleri.",
        specialties: ["B1-1", "B1-2", "B2-1", "B2-2", "C1-1"]
      },
      {
        slug: "halit-taner",
        name: "Halit Taner",
        since: 2014,
        rating: 4.8,
        privatePrice: 2850,
        groupPrice: 1425,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "B2 ve C1 seviyelerinde ders veriyor.",
        specialties: ["B2-1", "B2-2", "C1-1", "C1-2"]
      },
      {
        slug: "timur-yalaz",
        name: "Timur Yalaz",
        since: 2014,
        rating: 4.8,
        privatePrice: 2900,
        groupPrice: 1450,
        corporate: true,
        online: true,
        location: "Ankara",
        bio: "Ankara'da B2, B1 ve A2 seviyeleri.",
        specialties: ["A2-1", "A2-2", "B1-1", "B1-2", "B2-1"]
      },
      {
        slug: "seniz-gok",
        name: "Şeniz Gök",
        since: 2015,
        rating: 4.7,
        privatePrice: 2750,
        groupPrice: 1375,
        corporate: true,
        online: true,
        location: "İzmir",
        bio: "İzmir'de B2 ve C1 seviyeleri.",
        specialties: ["B2-1", "B2-2", "C1-1", "C1-2"]
      },
      {
        slug: "gurkan-sahbaz",
        name: "Gürkan Şahbaz",
        since: 2015,
        rating: 4.7,
        privatePrice: 2800,
        groupPrice: 1400,
        corporate: true,
        online: true,
        location: "Bursa",
        bio: "Bursa'da B2, B1 ve konuşma pratiği.",
        specialties: ["B1-1", "B1-2", "B2-1", "B2-2", "Konuşma Pratiği"]
      },
      {
        slug: "cigdem-berksoy",
        name: "Çiğdem Berksoy",
        since: 2017,
        rating: 4.7,
        privatePrice: 2750,
        groupPrice: 1375,
        corporate: true,
        online: true,
        location: "Eskişehir",
        bio: "Eskişehir'de B2 ve B1 seviyeleri.",
        specialties: ["B1-1", "B1-2", "B2-1", "Konuşma Pratiği"]
      },
      {
        slug: "mujdat-alp",
        name: "Müjdat Alp",
        since: 2015,
        rating: 4.7,
        privatePrice: 2800,
        groupPrice: 1400,
        corporate: true,
        online: true,
        location: "Kocaeli",
        bio: "Kocaeli'de B2, C1 ve konuşma pratiği.",
        specialties: ["B2-1", "B2-2", "C1-1", "Konuşma Pratiği"]
      },
      {
        slug: "reyhan-yildirim",
        name: "Reyhan Yıldırım",
        since: 2014,
        rating: 4.9,
        privatePrice: 3100,
        groupPrice: 1550,
        corporate: true,
        online: true,
        location: "Gaziantep",
        bio: "Gaziantep'te B2, C1 ve konuşma pratiği.",
        specialties: ["B1-1", "B1-2", "B2-1", "B2-2", "C1-1", "Konuşma Pratiği"]
      }
    ],
    description: "B2 seviyesi İngilizce, orta-ileri düzeyde dil bilgisi ve akıcı konuşma becerileri kazandırır. B2-1 ve B2-2 alt seviyelerini kapsar.",
    whyTake: "Akademik ve profesyonel İngilizce için gereklidir.",
    employmentAreas: "İş İngilizcesi, uluslararası şirketler, yüksek lisans.",
    requirements: "B1 seviyesini tamamlamış olmak."
  },
  {
    slug: "c1-seviyesi-ingilizce",
    title: "C1 Seviyesi İngilizce (C1-1 / C1-2) İleri Seviye",
    category: "Dil Eğitimi",
    breadcrumb: "Dil Eğitimi > İngilizce > C1 İleri",
    image: "/images/ingilizce.jpg",
    instructors: [
      {
        slug: "serhat-kose",
        name: "Serhat Köse",
        since: 2012,
        rating: 5.0,
        privatePrice: 3800,
        groupPrice: 1900,
        corporate: true,
        online: true,
        location: "İstanbul Anadolu Yakası",
        bio: "C1 ve C2 seviyelerinde uzman, akademik İngilizce.",
        specialties: ["C1-1", "C1-2", "C2-1", "C2-2"]
      },
      {
        slug: "taner-simsek",
        name: "Taner Şimşek",
        since: 2013,
        rating: 4.9,
        privatePrice: 3700,
        groupPrice: 1850,
        corporate: true,
        online: true,
        location: "İstanbul Anadolu Yakası",
        bio: "C1 ve B2 seviyelerinde ders veriyor.",
        specialties: ["B2-1", "B2-2", "C1-1", "Konuşma Pratiği"]
      },
      {
        slug: "kutay-sonmez",
        name: "Kutay Sönmez",
        since: 2013,
        rating: 4.9,
        privatePrice: 3800,
        groupPrice: 1900,
        corporate: true,
        online: true,
        location: "İstanbul Anadolu Yakası",
        bio: "C1 ve C2 seviyelerinde uzman.",
        specialties: ["C1-1", "C1-2", "C2-1"]
      },
      {
        slug: "hande-bilgin",
        name: "Hande Bilgin",
        since: 2015,
        rating: 4.8,
        privatePrice: 3600,
        groupPrice: 1800,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "C1, B2 ve konuşma pratiği.",
        specialties: ["B2-1", "B2-2", "C1-1", "C1-2", "Konuşma Pratiği"]
      },
      {
        slug: "rana-tekin",
        name: "Rana Tekin",
        since: 2014,
        rating: 4.8,
        privatePrice: 3600,
        groupPrice: 1800,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "C1 ve C2 seviyelerinde eğitmen.",
        specialties: ["C1-1", "C1-2", "C2-1"]
      },
      {
        slug: "atilla-ozcan",
        name: "Atilla Özcan",
        since: 2013,
        rating: 4.9,
        privatePrice: 3800,
        groupPrice: 1900,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "C1, B2 ve B1 seviyeleri.",
        specialties: ["B1-1", "B1-2", "B2-1", "B2-2", "C1-1"]
      },
      {
        slug: "cuneyt-ertugrul",
        name: "Cüneyt Ertuğrul",
        since: 2015,
        rating: 4.6,
        privatePrice: 3500,
        groupPrice: 1750,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "C1 ve konuşma pratiği dersleri.",
        specialties: ["B1-1", "B1-2", "C1-1", "Konuşma Pratiği"]
      },
      {
        slug: "halit-taner",
        name: "Halit Taner",
        since: 2014,
        rating: 4.8,
        privatePrice: 3700,
        groupPrice: 1850,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "C1 ve B2 seviyeleri.",
        specialties: ["B2-1", "B2-2", "C1-1", "C1-2"]
      },
      {
        slug: "burcu-aktas",
        name: "Burcu Aktaş",
        since: 2016,
        rating: 4.7,
        privatePrice: 3500,
        groupPrice: 1750,
        corporate: true,
        online: true,
        location: "Ankara",
        bio: "Ankara'da C1 ve konuşma pratiği.",
        specialties: ["C1-1", "C1-2", "Konuşma Pratiği"]
      },
      {
        slug: "lale-sozen",
        name: "Lale Sözen",
        since: 2015,
        rating: 4.9,
        privatePrice: 3900,
        groupPrice: 1950,
        corporate: true,
        online: true,
        location: "Ankara",
        bio: "Ankara'da C1 ve C2 seviyeleri.",
        specialties: ["C1-1", "C1-2", "C2-1"]
      },
      {
        slug: "seniz-gok",
        name: "Şeniz Gök",
        since: 2015,
        rating: 4.7,
        privatePrice: 3600,
        groupPrice: 1800,
        corporate: true,
        online: true,
        location: "İzmir",
        bio: "İzmir'de C1 ve B2 seviyeleri.",
        specialties: ["B2-1", "B2-2", "C1-1", "C1-2"]
      },
      {
        slug: "eralp-komurcu",
        name: "Eralp Kömürcü",
        since: 2014,
        rating: 4.9,
        privatePrice: 4000,
        groupPrice: 2000,
        corporate: true,
        online: true,
        location: "İzmir",
        bio: "İzmir'de C1 ve C2 seviyeleri, tüm seviyeler.",
        specialties: ["C1-1", "C1-2", "C2-1", "C2-2"]
      },
      {
        slug: "ahu-tanriverdi",
        name: "Ahu Tanrıverdi",
        since: 2016,
        rating: 4.7,
        privatePrice: 3500,
        groupPrice: 1750,
        corporate: true,
        online: true,
        location: "Antalya",
        bio: "Antalya'da C1 ve konuşma pratiği.",
        specialties: ["C1-1", "C1-2", "Konuşma Pratiği"]
      },
      {
        slug: "savas-duman",
        name: "Savaş Duman",
        since: 2015,
        rating: 4.8,
        privatePrice: 3700,
        groupPrice: 1850,
        corporate: true,
        online: true,
        location: "Eskişehir",
        bio: "Eskişehir'de C1 ve C2 seviyeleri.",
        specialties: ["C1-1", "C1-2", "C2-1"]
      },
      {
        slug: "mujdat-alp",
        name: "Müjdat Alp",
        since: 2015,
        rating: 4.7,
        privatePrice: 3600,
        groupPrice: 1800,
        corporate: true,
        online: true,
        location: "Kocaeli",
        bio: "Kocaeli'de C1 ve B2 seviyeleri.",
        specialties: ["B2-1", "B2-2", "C1-1", "Konuşma Pratiği"]
      },
      {
        slug: "oylum-sari",
        name: "Oylum Sarı",
        since: 2015,
        rating: 4.9,
        privatePrice: 4000,
        groupPrice: 2000,
        corporate: true,
        online: true,
        location: "Adana",
        bio: "Adana'da C1 ve C2 seviyeleri.",
        specialties: ["C1-1", "C1-2", "C2-1", "C2-2"]
      },
      {
        slug: "reyhan-yildirim",
        name: "Reyhan Yıldırım",
        since: 2014,
        rating: 4.9,
        privatePrice: 3900,
        groupPrice: 1950,
        corporate: true,
        online: true,
        location: "Gaziantep",
        bio: "Gaziantep'te C1, B2 ve konuşma pratiği.",
        specialties: ["B1-1", "B1-2", "B2-1", "B2-2", "C1-1", "Konuşma Pratiği"]
      }
    ],
    description: "C1 seviyesi İngilizce, ileri düzeyde dil bilgisi, akademik yazma ve konuşma becerileri kazandırır. C1-1 ve C1-2 alt seviyelerini kapsar.",
    whyTake: "Akademik kariyer ve profesyonel İngilizce için gereklidir.",
    employmentAreas: "Akademisyenlik, yöneticilik, çevirmenlik.",
    requirements: "B2 seviyesini tamamlamış olmak."
  },
  {
    slug: "c2-seviyesi-ingilizce",
    title: "C2 Seviyesi İngilizce (C2-1 / C2-2) Profesyonel Seviye",
    category: "Dil Eğitimi",
    breadcrumb: "Dil Eğitimi > İngilizce > C2 Profesyonel",
    image: "/images/ingilizce.jpg",
    instructors: [
      {
        slug: "serhat-kose",
        name: "Serhat Köse",
        since: 2012,
        rating: 5.0,
        privatePrice: 5000,
        groupPrice: 2500,
        corporate: true,
        online: true,
        location: "İstanbul Anadolu Yakası",
        bio: "C2 seviyesinde uzman, akademik İngilizce.",
        specialties: ["C1-1", "C1-2", "C2-1", "C2-2"]
      },
      {
        slug: "kutay-sonmez",
        name: "Kutay Sönmez",
        since: 2013,
        rating: 4.9,
        privatePrice: 4800,
        groupPrice: 2400,
        corporate: true,
        online: true,
        location: "İstanbul Anadolu Yakası",
        bio: "C2 ve C1 seviyelerinde uzman.",
        specialties: ["C1-1", "C1-2", "C2-1"]
      },
      {
        slug: "jale-isik",
        name: "Jale Işık",
        since: 2012,
        rating: 5.0,
        privatePrice: 5200,
        groupPrice: 2600,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "Tüm ileri seviyelerde uzman, yılların deneyimi.",
        specialties: ["C1-1", "C1-2", "C2-1", "C2-2"]
      },
      {
        slug: "rana-tekin",
        name: "Rana Tekin",
        since: 2014,
        rating: 4.8,
        privatePrice: 4700,
        groupPrice: 2350,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "C2 ve C1 seviyelerinde eğitmen.",
        specialties: ["C1-1", "C1-2", "C2-1"]
      },
      {
        slug: "sezai-gundogdu",
        name: "Sezai Gündoğdu",
        since: 2011,
        rating: 5.0,
        privatePrice: 5500,
        groupPrice: 2750,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "C2 seviyesinde uzman, akademik danışman.",
        specialties: ["C1-1", "C1-2", "C2-1", "C2-2"]
      },
      {
        slug: "lale-sozen",
        name: "Lale Sözen",
        since: 2015,
        rating: 4.9,
        privatePrice: 4900,
        groupPrice: 2450,
        corporate: true,
        online: true,
        location: "Ankara",
        bio: "Ankara'da C2 ve C1 seviyeleri.",
        specialties: ["C1-1", "C1-2", "C2-1"]
      },
      {
        slug: "eralp-komurcu",
        name: "Eralp Kömürcü",
        since: 2014,
        rating: 4.9,
        privatePrice: 5000,
        groupPrice: 2500,
        corporate: true,
        online: true,
        location: "İzmir",
        bio: "İzmir'de C2 ve C1 seviyeleri, tüm seviyeler.",
        specialties: ["C1-1", "C1-2", "C2-1", "C2-2"]
      },
      {
        slug: "oylum-sari",
        name: "Oylum Sarı",
        since: 2015,
        rating: 4.9,
        privatePrice: 5000,
        groupPrice: 2500,
        corporate: true,
        online: true,
        location: "Adana",
        bio: "Adana'da C2 ve C1 seviyeleri.",
        specialties: ["C1-1", "C1-2", "C2-1", "C2-2"]
      }
    ],
    description: "C2 seviyesi İngilizce, anadil seviyesinde akıcılık, akademik yazma ve ileri düzey iletişim becerileri kazandırır. C2-1 ve C2-2 alt seviyelerini kapsar.",
    whyTake: "Anadil seviyesinde İngilizce için son adım.",
    employmentAreas: "Akademisyenlik, üst düzey yöneticilik, çevirmenlik.",
    requirements: "C1 seviyesini tamamlamış olmak."
  },
  {
    slug: "ingilizce-konusma-pratigi",
    title: "İngilizce Konuşma Pratiği",
    category: "Dil Eğitimi",
    breadcrumb: "Dil Eğitimi > İngilizce > Konuşma Pratiği",
    image: "/images/ingilizce.jpg",
    instructors: [
      {
        slug: "duygu-ozer",
        name: "Duygu Özer",
        since: 2014,
        rating: 4.8,
        privatePrice: 2500,
        groupPrice: 1250,
        corporate: true,
        online: true,
        location: "İstanbul Anadolu Yakası",
        bio: "Konuşma pratiğinde uzman, akıcılık kazandırma.",
        specialties: ["B1-1", "B1-2", "B2-1", "Konuşma Pratiği"]
      },
      {
        slug: "taner-simsek",
        name: "Taner Şimşek",
        since: 2013,
        rating: 4.9,
        privatePrice: 2600,
        groupPrice: 1300,
        corporate: true,
        online: true,
        location: "İstanbul Anadolu Yakası",
        bio: "Konuşma pratiği ve B2-C1 seviyeleri.",
        specialties: ["B2-1", "B2-2", "C1-1", "Konuşma Pratiği"]
      },
      {
        slug: "cemalettin-kaya",
        name: "Cemalettin Kaya",
        since: 2014,
        rating: 4.8,
        privatePrice: 2400,
        groupPrice: 1200,
        corporate: true,
        online: true,
        location: "İstanbul Anadolu Yakası",
        bio: "Konuşma pratiği ve A2 seviyeleri.",
        specialties: ["A1-1", "A1-2", "A2-1", "A2-2", "Konuşma Pratiği"]
      },
      {
        slug: "ozgur-eren",
        name: "Özgür Eren",
        since: 2015,
        rating: 4.7,
        privatePrice: 2400,
        groupPrice: 1200,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "Konuşma pratiği ve B1-B2 seviyeleri.",
        specialties: ["B1-1", "B1-2", "B2-1", "Konuşma Pratiği"]
      },
      {
        slug: "hande-bilgin",
        name: "Hande Bilgin",
        since: 2015,
        rating: 4.8,
        privatePrice: 2600,
        groupPrice: 1300,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "Konuşma pratiği, B2 ve C1 seviyeleri.",
        specialties: ["B2-1", "B2-2", "C1-1", "C1-2", "Konuşma Pratiği"]
      },
      {
        slug: "cuneyt-ertugrul",
        name: "Cüneyt Ertuğrul",
        since: 2015,
        rating: 4.6,
        privatePrice: 2300,
        groupPrice: 1150,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "Konuşma pratiği ve B1-C1 seviyeleri.",
        specialties: ["B1-1", "B1-2", "C1-1", "Konuşma Pratiği"]
      },
      {
        slug: "belma-karaca",
        name: "Belma Karaca",
        since: 2016,
        rating: 4.7,
        privatePrice: 2400,
        groupPrice: 1200,
        corporate: true,
        online: true,
        location: "İstanbul Avrupa Yakası",
        bio: "Konuşma pratiği ve A1-B1 seviyeleri.",
        specialties: ["A1-1", "A1-2", "B1-1", "Konuşma Pratiği"]
      },
      {
        slug: "burcu-aktas",
        name: "Burcu Aktaş",
        since: 2016,
        rating: 4.7,
        privatePrice: 2500,
        groupPrice: 1250,
        corporate: true,
        online: true,
        location: "Ankara",
        bio: "Ankara'da konuşma pratiği ve C1 seviyeleri.",
        specialties: ["C1-1", "C1-2", "Konuşma Pratiği"]
      },
      {
        slug: "ercan-toprak",
        name: "Ercan Toprak",
        since: 2018,
        rating: 4.5,
        privatePrice: 2200,
        groupPrice: 1100,
        corporate: false,
        online: true,
        location: "İzmir",
        bio: "İzmir'de konuşma pratiği ve A1-A2 seviyeleri.",
        specialties: ["A1-1", "A1-2", "A2-1", "Konuşma Pratiği"]
      },
      {
        slug: "gurkan-sahbaz",
        name: "Gürkan Şahbaz",
        since: 2015,
        rating: 4.7,
        privatePrice: 2500,
        groupPrice: 1250,
        corporate: true,
        online: true,
        location: "Bursa",
        bio: "Bursa'da konuşma pratiği ve B1-B2 seviyeleri.",
        specialties: ["B1-1", "B1-2", "B2-1", "B2-2", "Konuşma Pratiği"]
      },
      {
        slug: "ahu-tanriverdi",
        name: "Ahu Tanrıverdi",
        since: 2016,
        rating: 4.7,
        privatePrice: 2500,
        groupPrice: 1250,
        corporate: true,
        online: true,
        location: "Antalya",
        bio: "Antalya'da konuşma pratiği ve C1 seviyeleri.",
        specialties: ["C1-1", "C1-2", "Konuşma Pratiği"]
      },
      {
        slug: "cigdem-berksoy",
        name: "Çiğdem Berksoy",
        since: 2017,
        rating: 4.7,
        privatePrice: 2400,
        groupPrice: 1200,
        corporate: true,
        online: true,
        location: "Eskişehir",
        bio: "Eskişehir'de konuşma pratiği ve B1-B2 seviyeleri.",
        specialties: ["B1-1", "B1-2", "B2-1", "Konuşma Pratiği"]
      },
      {
        slug: "mujdat-alp",
        name: "Müjdat Alp",
        since: 2015,
        rating: 4.7,
        privatePrice: 2600,
        groupPrice: 1300,
        corporate: true,
        online: true,
        location: "Kocaeli",
        bio: "Kocaeli'de konuşma pratiği ve B2-C1 seviyeleri.",
        specialties: ["B2-1", "B2-2", "C1-1", "Konuşma Pratiği"]
      },
      {
        slug: "reyhan-yildirim",
        name: "Reyhan Yıldırım",
        since: 2014,
        rating: 4.9,
        privatePrice: 2800,
        groupPrice: 1400,
        corporate: true,
        online: true,
        location: "Gaziantep",
        bio: "Gaziantep'te konuşma pratiği ve B1-C1 seviyeleri.",
        specialties: ["B1-1", "B1-2", "B2-1", "B2-2", "C1-1", "Konuşma Pratiği"]
      }
    ],
    description: "İngilizce konuşma pratiği dersleri, akıcılık kazanmak ve günlük konuşmalarda kendinizi rahat ifade etmek için tasarlanmıştır.",
    whyTake: "Konuşma becerinizi geliştirerek İngilizceyi aktif olarak kullanın.",
    employmentAreas: "Her seviyede İngilizce gerektiren işler.",
    requirements: "En az A2 seviyesinde İngilizce bilgisi önerilir."
  },

  // ===== ALMANCA DERSLERİ =====

// A1 Almanca
{
  slug: "a1-seviyesi-almanca",
  title: "A1 Seviyesi Almanca (A1-1 / A1-2) Temel Seviye",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Almanca > A1 Temel",
  image: "/images/almanca.jpg",
  instructors: [
    {
      slug: "orhan-kunt",
      name: "Orhan Kunt",
      since: 2015,
      rating: 4.7,
      privatePrice: 1200,
      groupPrice: 600,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "A1-A2 seviyelerinde uzman Almanca öğretmeni.",
      specialties: ["A1-1 Almanca Dersi", "A1-2 Almanca Dersi", "A2-1 Almanca Dersi"]
    },
    {
      slug: "guzin-okay",
      name: "Güzin Okay",
      since: 2017,
      rating: 4.5,
      privatePrice: 1150,
      groupPrice: 575,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "A1 seviyesinde uzman, başlangıç dersleri.",
      specialties: ["A1-1 Almanca Dersi", "A1-2 Almanca Dersi"]
    },
    {
      slug: "seher-ates",
      name: "Seher Ateş",
      since: 2016,
      rating: 4.8,
      privatePrice: 1300,
      groupPrice: 650,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "A1-A2 seviyelerinde deneyimli eğitmen.",
      specialties: ["A1-1 Almanca Dersi", "A1-2 Almanca Dersi", "A2-1 Almanca Dersi", "A2-2 Almanca Dersi"]
    },
    {
      slug: "izzet-capkin",
      name: "İzzet Çapkın",
      since: 2018,
      rating: 4.6,
      privatePrice: 1100,
      groupPrice: 550,
      corporate: false,
      online: true,
      location: "Ankara",
      bio: "Ankara'da A1 seviyesinde Almanca dersleri.",
      specialties: ["A1-1 Almanca Dersi", "A1-2 Almanca Dersi"]
    }
  ],
  description: "A1 seviyesi Almanca, temel dil bilgisi ve günlük konuşma becerilerini kapsar. A1-1 ve A1-2 alt seviyelerini içerir.",
  whyTake: "Almancaya sıfırdan başlamak için ideal.",
  employmentAreas: "Temel Almanca gerektiren işler, seyahat.",
  requirements: "Hiçbir ön koşul yoktur."
},

// A2 Almanca
{
  slug: "a2-seviyesi-almanca",
  title: "A2 Seviyesi Almanca (A2-1 / A2-2) Temel Seviye",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Almanca > A2 Temel",
  image: "/images/almanca.jpg",
  instructors: [
    {
      slug: "orhan-kunt",
      name: "Orhan Kunt",
      since: 2015,
      rating: 4.7,
      privatePrice: 1500,
      groupPrice: 750,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "A1-A2 seviyelerinde uzman Almanca öğretmeni.",
      specialties: ["A1-1 Almanca Dersi", "A1-2 Almanca Dersi", "A2-1 Almanca Dersi"]
    },
    {
      slug: "nurten-ece",
      name: "Nurten Ece",
      since: 2016,
      rating: 4.6,
      privatePrice: 1550,
      groupPrice: 775,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "A2 ve B1 seviyelerinde ders veriyor.",
      specialties: ["A2-1 Almanca Dersi", "A2-2 Almanca Dersi", "B1-1 Almanca Dersi"]
    },
    {
      slug: "irfan-basaran",
      name: "İrfan Başaran",
      since: 2015,
      rating: 4.7,
      privatePrice: 1500,
      groupPrice: 750,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "A2 ve konuşma pratiği dersleri.",
      specialties: ["A2-1 Almanca Dersi", "A2-2 Almanca Dersi", "Almanca Konuşma Pratiği"]
    },
    {
      slug: "seher-ates",
      name: "Seher Ateş",
      since: 2016,
      rating: 4.8,
      privatePrice: 1600,
      groupPrice: 800,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "A1-A2 seviyelerinde deneyimli eğitmen.",
      specialties: ["A1-1 Almanca Dersi", "A1-2 Almanca Dersi", "A2-1 Almanca Dersi", "A2-2 Almanca Dersi"]
    },
    {
      slug: "atilla-poyraz",
      name: "Atilla Poyraz",
      since: 2016,
      rating: 4.6,
      privatePrice: 1500,
      groupPrice: 750,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "A2 ve B1 seviyelerinde ders veriyor.",
      specialties: ["A2-1 Almanca Dersi", "A2-2 Almanca Dersi", "B1-1 Almanca Dersi"]
    },
    {
      slug: "figen-unal",
      name: "Figen Ünal",
      since: 2017,
      rating: 4.5,
      privatePrice: 1400,
      groupPrice: 700,
      corporate: false,
      online: true,
      location: "Bursa",
      bio: "Bursa'da A2 ve B1 seviyelerinde Almanca dersleri.",
      specialties: ["A2-1 Almanca Dersi", "A2-2 Almanca Dersi", "B1-1 Almanca Dersi"]
    }
  ],
  description: "A2 seviyesi Almanca, temel dil bilgisini pekiştirir ve basit iletişim kurmayı sağlar. A2-1 ve A2-2 alt seviyelerini kapsar.",
  whyTake: "A1'i tamamlayanlar için sonraki adım.",
  employmentAreas: "Temel Almanca gerektiren işler, turizm.",
  requirements: "A1 seviyesini tamamlamış olmak."
},

// B1 Almanca
{
  slug: "b1-seviyesi-almanca",
  title: "B1 Seviyesi Almanca (B1-1 / B1-2) Orta Seviye",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Almanca > B1 Orta",
  image: "/images/almanca.jpg",
  instructors: [
    {
      slug: "gusen-tuzun",
      name: "Gülşen Tüzün",
      since: 2014,
      rating: 4.8,
      privatePrice: 2200,
      groupPrice: 1100,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "B1 ve konuşma pratiğinde uzman.",
      specialties: ["B1-1 Almanca Dersi", "B1-2 Almanca Dersi", "Almanca Konuşma Pratiği"]
    },
    {
      slug: "nurten-ece",
      name: "Nurten Ece",
      since: 2016,
      rating: 4.6,
      privatePrice: 2100,
      groupPrice: 1050,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "A2 ve B1 seviyelerinde ders veriyor.",
      specialties: ["A2-1 Almanca Dersi", "A2-2 Almanca Dersi", "B1-1 Almanca Dersi"]
    },
    {
      slug: "muge-suer",
      name: "Müge Süer",
      since: 2015,
      rating: 4.7,
      privatePrice: 2200,
      groupPrice: 1100,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "B1 ve B2 seviyelerinde ders veriyor.",
      specialties: ["B1-1 Almanca Dersi", "B1-2 Almanca Dersi", "B2-1 Almanca Dersi"]
    },
    
    {
      slug: "onder-ozdil",
      name: "Önder Özdil",
      since: 2016,
      rating: 4.7,
      privatePrice: 2100,
      groupPrice: 1050,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "B1 ve konuşma pratiği dersleri.",
      specialties: ["B1-1 Almanca Dersi", "B1-2 Almanca Dersi", "Almanca Konuşma Pratiği"]
    },
    {
      slug: "atilla-poyraz",
      name: "Atilla Poyraz",
      since: 2016,
      rating: 4.6,
      privatePrice: 2000,
      groupPrice: 1000,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "A2 ve B1 seviyelerinde ders veriyor.",
      specialties: ["A2-1 Almanca Dersi", "A2-2 Almanca Dersi", "B1-1 Almanca Dersi"]
    },
    {
      slug: "ruhsar-dincer",
      name: "Ruhsar Dinçer",
      since: 2015,
      rating: 4.7,
      privatePrice: 2100,
      groupPrice: 1050,
      corporate: true,
      online: true,
      location: "Ankara",
      bio: "Ankara'da B1 ve konuşma pratiği dersleri.",
      specialties: ["B1-1 Almanca Dersi", "B1-2 Almanca Dersi", "Almanca Konuşma Pratiği"]
    },
    {
      slug: "figen-unal",
      name: "Figen Ünal",
      since: 2017,
      rating: 4.5,
      privatePrice: 1900,
      groupPrice: 950,
      corporate: false,
      online: true,
      location: "Bursa",
      bio: "Bursa'da A2 ve B1 seviyelerinde Almanca dersleri.",
      specialties: ["A2-1 Almanca Dersi", "A2-2 Almanca Dersi", "B1-1 Almanca Dersi"]
    }
  ],
  description: "B1 seviyesi Almanca, orta düzeyde dil bilgisi ve günlük konuşma becerilerini geliştirir. B1-1 ve B1-2 alt seviyelerini kapsar.",
  whyTake: "Almanca'yı akıcı konuşmaya başlamak için.",
  employmentAreas: "Müşteri hizmetleri, turizm, eğitim.",
  requirements: "A2 seviyesini tamamlamış olmak."
},

// B2 Almanca
{
  slug: "b2-seviyesi-almanca",
  title: "B2 Seviyesi Almanca (B2-1 / B2-2) Orta-İleri Seviye",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Almanca > B2 Orta-İleri",
  image: "/images/almanca.jpg",
  instructors: [
    {
      slug: "yekta-ozsan",
      name: "Yekta Özsan",
      since: 2014,
      rating: 4.8,
      privatePrice: 2800,
      groupPrice: 1400,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "B2, C1 ve konuşma pratiği dersleri.",
      specialties: ["B2-1 Almanca Dersi", "B2-2 Almanca Dersi", "C1-1 Almanca Dersi", "Almanca Konuşma Pratiği"]
    },
    {
      slug: "muge-suer",
      name: "Müge Süer",
      since: 2015,
      rating: 4.7,
      privatePrice: 2700,
      groupPrice: 1350,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "B1 ve B2 seviyelerinde ders veriyor.",
      specialties: ["B1-1 Almanca Dersi", "B1-2 Almanca Dersi", "B2-1 Almanca Dersi"]
    },
        {
      slug: "sema-kabak",
      name: "Sema Kabak",
      since: 2015,
      rating: 4.7,
      privatePrice: 2800,
      groupPrice: 1400,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "B2 ve C1 seviyelerinde ders veriyor.",
      specialties: ["B2-1 Almanca Dersi", "B2-2 Almanca Dersi", "C1-1 Almanca Dersi"]
    }
  ],
  description: "B2 seviyesi Almanca, orta-ileri düzeyde dil bilgisi ve akıcı konuşma becerileri kazandırır. B2-1 ve B2-2 alt seviyelerini kapsar.",
  whyTake: "Akademik ve profesyonel Almanca için gereklidir.",
  employmentAreas: "İş Almancası, uluslararası şirketler.",
  requirements: "B1 seviyesini tamamlamış olmak."
},

// C1 Almanca
{
  slug: "c1-seviyesi-almanca",
  title: "C1 Seviyesi Almanca (C1-1 / C1-2) İleri Seviye",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Almanca > C1 İleri",
  image: "/images/almanca.jpg",
  instructors: [
    {
      slug: "fahri-coskun",
      name: "Fahri Coşkun",
      since: 2013,
      rating: 4.9,
      privatePrice: 3800,
      groupPrice: 1900,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "C1-C2 seviyelerinde uzman.",
      specialties: ["C1-1 Almanca Dersi", "C1-2 Almanca Dersi", "C2-1 Almanca Dersi"]
    },
    {
      slug: "yekta-ozsan",
      name: "Yekta Özsan",
      since: 2014,
      rating: 4.8,
      privatePrice: 3600,
      groupPrice: 1800,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "B2, C1 ve konuşma pratiği dersleri.",
      specialties: ["B2-1 Almanca Dersi", "B2-2 Almanca Dersi", "C1-1 Almanca Dersi", "Almanca Konuşma Pratiği"]
    },
    {
      slug: "jale-evrim",
      name: "Jale Evrim",
      since: 2013,
      rating: 4.9,
      privatePrice: 3900,
      groupPrice: 1950,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "C1-C2 seviyelerinde ders veriyor.",
      specialties: ["C1-1 Almanca Dersi", "C1-2 Almanca Dersi", "C2-1 Almanca Dersi"]
    },
    {
      slug: "necla-berksoy",
      name: "Necla Berksoy",
      since: 2012,
      rating: 5.0,
      privatePrice: 4200,
      groupPrice: 2100,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "C1-C2 tüm seviyelerde uzman.",
      specialties: ["C1-1 Almanca Dersi", "C1-2 Almanca Dersi", "C2-1 Almanca Dersi", "C2-2 Almanca Dersi"]
    },
    {
      slug: "sema-kabak",
      name: "Sema Kabak",
      since: 2015,
      rating: 4.7,
      privatePrice: 3500,
      groupPrice: 1750,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "B2 ve C1 seviyelerinde ders veriyor.",
      specialties: ["B2-1 Almanca Dersi", "B2-2 Almanca Dersi", "C1-1 Almanca Dersi"]
    },
    {
      slug: "tolga-ozkok",
      name: "Tolga Özkök",
      since: 2014,
      rating: 4.8,
      privatePrice: 3700,
      groupPrice: 1850,
      corporate: true,
      online: true,
      location: "İzmir",
      bio: "İzmir'de C1-C2 seviyelerinde ders veriyor.",
      specialties: ["C1-1 Almanca Dersi", "C1-2 Almanca Dersi", "C2-1 Almanca Dersi"]
    }
  ],
  description: "C1 seviyesi Almanca, ileri düzeyde dil bilgisi, akademik yazma ve konuşma becerileri kazandırır. C1-1 ve C1-2 alt seviyelerini kapsar.",
  whyTake: "Akademik kariyer ve profesyonel Almanca için.",
  employmentAreas: "Akademisyenlik, yöneticilik, çevirmenlik.",
  requirements: "B2 seviyesini tamamlamış olmak."
},

// C2 Almanca
{
  slug: "c2-seviyesi-almanca",
  title: "C2 Seviyesi Almanca (C2-1 / C2-2) Profesyonel Seviye",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Almanca > C2 Profesyonel",
  image: "/images/almanca.jpg",
  instructors: [
    {
      slug: "fahri-coskun",
      name: "Fahri Coşkun",
      since: 2013,
      rating: 4.9,
      privatePrice: 4800,
      groupPrice: 2400,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "C1-C2 seviyelerinde uzman.",
      specialties: ["C1-1 Almanca Dersi", "C1-2 Almanca Dersi", "C2-1 Almanca Dersi"]
    },
    {
      slug: "tanju-cuce",
      name: "Tanju Cüce",
      since: 2014,
      rating: 4.8,
      privatePrice: 4700,
      groupPrice: 2350,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "C2 seviyesinde uzman.",
      specialties: ["C2-1 Almanca Dersi", "C2-2 Almanca Dersi"]
    },
    {
      slug: "jale-evrim",
      name: "Jale Evrim",
      since: 2013,
      rating: 4.9,
      privatePrice: 4900,
      groupPrice: 2450,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "C1-C2 seviyelerinde ders veriyor.",
      specialties: ["C1-1 Almanca Dersi", "C1-2 Almanca Dersi", "C2-1 Almanca Dersi"]
    },
    {
      slug: "necla-berksoy",
      name: "Necla Berksoy",
      since: 2012,
      rating: 5.0,
      privatePrice: 5200,
      groupPrice: 2600,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "C1-C2 tüm seviyelerde uzman.",
      specialties: ["C1-1 Almanca Dersi", "C1-2 Almanca Dersi", "C2-1 Almanca Dersi", "C2-2 Almanca Dersi"]
    },
    {
      slug: "tolga-ozkok",
      name: "Tolga Özkök",
      since: 2014,
      rating: 4.8,
      privatePrice: 4800,
      groupPrice: 2400,
      corporate: true,
      online: true,
      location: "İzmir",
      bio: "İzmir'de C1-C2 seviyelerinde ders veriyor.",
      specialties: ["C1-1 Almanca Dersi", "C1-2 Almanca Dersi", "C2-1 Almanca Dersi"]
    }
  ],
  description: "C2 seviyesi Almanca, anadil seviyesinde akıcılık, ileri düzey iletişim becerileri kazandırır. C2-1 ve C2-2 alt seviyelerini kapsar.",
  whyTake: "Almanca'da uzmanlaşmak için.",
  employmentAreas: "Akademisyenlik, üst düzey yöneticilik, çevirmenlik.",
  requirements: "C1 seviyesini tamamlamış olmak."
},

// Almanca Konuşma Pratiği
{
  slug: "almanca-konusma-pratigi",
  title: "Almanca Konuşma Pratiği",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Almanca > Konuşma Pratiği",
  image: "/images/almanca.jpg",
  instructors: [
    {
      slug: "gulseren-tuzun",
      name: "Gülseren Tüzün",
      since: 2014,
      rating: 4.8,
      privatePrice: 2400,
      groupPrice: 1200,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "B1 ve konuşma pratiğinde uzman.",
      specialties: ["B1-1 Almanca Dersi", "B1-2 Almanca Dersi", "Almanca Konuşma Pratiği"]
    },
    {
      slug: "yekta-ozsan",
      name: "Yekta Özsan",
      since: 2014,
      rating: 4.8,
      privatePrice: 2600,
      groupPrice: 1300,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "B2, C1 ve konuşma pratiği dersleri.",
      specialties: ["B2-1 Almanca Dersi", "B2-2 Almanca Dersi", "C1-1 Almanca Dersi", "Almanca Konuşma Pratiği"]
    },
    {
      slug: "irfan-basaran",
      name: "İrfan Başaran",
      since: 2015,
      rating: 4.7,
      privatePrice: 2300,
      groupPrice: 1150,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "A2 ve konuşma pratiği dersleri.",
      specialties: ["A2-1 Almanca Dersi", "A2-2 Almanca Dersi", "Almanca Konuşma Pratiği"]
    },
    {
      slug: "kudret-sayar",
      name: "Kudret Sayar",
      since: 2014,
      rating: 4.9,
      privatePrice: 2800,
      groupPrice: 1400,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "B1, B2 ve konuşma pratiği dersleri.",
      specialties: ["B1-1 Almanca Dersi", "B1-2 Almanca Dersi", "B2-1 Almanca Dersi", "B2-2 Almanca Dersi", "Almanca Konuşma Pratiği"]
    },
    {
      slug: "onder-ozdil",
      name: "Önder Özdil",
      since: 2016,
      rating: 4.7,
      privatePrice: 2400,
      groupPrice: 1200,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "B1 ve konuşma pratiği dersleri.",
      specialties: ["B1-1 Almanca Dersi", "B1-2 Almanca Dersi", "Almanca Konuşma Pratiği"]
    },
    {
      slug: "ruhsar-dincer",
      name: "Ruhsar Dinçer",
      since: 2015,
      rating: 4.7,
      privatePrice: 2400,
      groupPrice: 1200,
      corporate: true,
      online: true,
      location: "Ankara",
      bio: "Ankara'da B1 ve konuşma pratiği dersleri.",
      specialties: ["B1-1 Almanca Dersi", "B1-2 Almanca Dersi", "Almanca Konuşma Pratiği"]
    }
  ],
  description: "Almanca konuşma pratiği dersleri, akıcılık kazanmak ve günlük konuşmalarda kendinizi rahat ifade etmek için tasarlanmıştır.",
  whyTake: "Konuşma becerinizi geliştirerek Almanca'yı aktif olarak kullanın.",
  employmentAreas: "Her seviyede Almanca gerektiren işler.",
  requirements: "En az A2 seviyesinde Almanca bilgisi önerilir."
},

// ===== ALMANCA KURSLARI =====
// A1 Seviyesi Almanca
{
  slug: "a1-seviyesi-almanca",
  title: "A1 Seviyesi Almanca (A1-1 / A1-2) Temel Seviye",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Almanca > A1 Temel",
  image: "/images/almanca.jpg",
  instructors: [
    {
      slug: "orhan-kunt",
      name: "Orhan Kunt",
      since: 2015,
      rating: 4.7,
      privatePrice: 1800,
      groupPrice: 900,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "A1 ve A2 seviyelerinde uzman, 8 yıllık deneyim.",
      specialties: ["A1-1", "A1-2", "A2-1"]
    },
    {
      slug: "guzin-okay",
      name: "Güzin Okay",
      since: 2017,
      rating: 4.5,
      privatePrice: 1600,
      groupPrice: 800,
      corporate: false,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "Başlangıç seviyesinde uzman, sabırlı ve anlaşılır anlatım.",
      specialties: ["A1-1", "A1-2"]
    },
    {
      slug: "seher-ates",
      name: "Seher Ateş",
      since: 2014,
      rating: 4.8,
      privatePrice: 2000,
      groupPrice: 1000,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "A1 ve A2 seviyelerinde deneyimli, konuşma ağırlıklı dersler.",
      specialties: ["A1-1", "A1-2", "A2-1", "A2-2"]
    },
    {
      slug: "izzet-capkin",
      name: "İzzet Çapkın",
      since: 2018,
      rating: 4.4,
      privatePrice: 1500,
      groupPrice: 750,
      corporate: false,
      online: true,
      location: "Ankara",
      bio: "Ankara'da A1 seviyesinde ders veriyor, yeni başlayanlar için ideal.",
      specialties: ["A1-1", "A1-2"]
    }
  ],
  description: "A1 seviyesi Almanca, temel dil bilgisi ve günlük konuşma becerilerini kapsar. A1-1 ve A1-2 alt seviyeleri işlenir.",
  whyTake: "Almancaya sıfırdan başlamak ve sağlam bir temel oluşturmak için idealdir.",
  employmentAreas: "Temel Almanca gerektiren işler, seyahat, günlük iletişim.",
  requirements: "Hiçbir ön koşul yoktur."
},
{
  slug: "a2-seviyesi-almanca",
  title: "A2 Seviyesi Almanca (A2-1 / A2-2) Temel Seviye",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Almanca > A2 Temel",
  image: "/images/almanca.jpg",
  instructors: [
    {
      slug: "orhan-kunt",
      name: "Orhan Kunt",
      since: 2015,
      rating: 4.7,
      privatePrice: 2200,
      groupPrice: 1100,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "A2 seviyesinde deneyimli, konuşma pratiğine önem verir.",
      specialties: ["A1-1", "A1-2", "A2-1"]
    },
    {
      slug: "nurten-ece",
      name: "Nurten Ece",
      since: 2016,
      rating: 4.6,
      privatePrice: 2100,
      groupPrice: 1050,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "A2 ve B1 seviyelerinde ders veriyor.",
      specialties: ["A2-1", "A2-2", "B1-1"]
    },
    {
      slug: "irfan-basaran",
      name: "İrfan Başaran",
      since: 2015,
      rating: 4.5,
      privatePrice: 2000,
      groupPrice: 1000,
      corporate: false,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "A2 ve konuşma pratiği dersleri.",
      specialties: ["A2-1", "A2-2", "Konuşma Pratiği"]
    },
    {
      slug: "seher-ates",
      name: "Seher Ateş",
      since: 2014,
      rating: 4.8,
      privatePrice: 2300,
      groupPrice: 1150,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "A2 seviyesinde uzun yıllar deneyim.",
      specialties: ["A1-1", "A1-2", "A2-1", "A2-2"]
    },
    {
      slug: "atilla-poyraz",
      name: "Atilla Poyraz",
      since: 2016,
      rating: 4.6,
      privatePrice: 2100,
      groupPrice: 1050,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "A2 ve B1 seviyelerinde ders veriyor.",
      specialties: ["A2-1", "A2-2", "B1-1"]
    },
    {
      slug: "figen-unal",
      name: "Figen Ünal",
      since: 2017,
      rating: 4.5,
      privatePrice: 2000,
      groupPrice: 1000,
      corporate: false,
      online: true,
      location: "Bursa",
      bio: "Bursa'da A2 ve B1 seviyelerinde dersler.",
      specialties: ["A2-1", "A2-2", "B1-1"]
    }
  ],
  description: "A2 seviyesi Almanca, temel dil bilgisini pekiştirir ve basit cümlelerle iletişim kurmayı sağlar. A2-1 ve A2-2 alt seviyelerini kapsar.",
  whyTake: "A1 seviyesini tamamlayanlar için bir sonraki adım.",
  employmentAreas: "Turizm, müşteri hizmetleri, temel iş Almancası.",
  requirements: "A1 seviyesini tamamlamış olmak."
},
{
  slug: "b1-seviyesi-almanca",
  title: "B1 Seviyesi Almanca (B1-1 / B1-2) Orta Seviye",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Almanca > B1 Orta",
  image: "/images/almanca.jpg",
  instructors: [
    {
      slug: "gulseren-tuzun",
      name: "Gülseren Tüzün",
      since: 2014,
      rating: 4.8,
      privatePrice: 2800,
      groupPrice: 1400,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "B1 ve konuşma pratiğinde uzman.",
      specialties: ["B1-1", "B1-2", "Konuşma Pratiği"]
    },
    {
      slug: "nurten-ece",
      name: "Nurten Ece",
      since: 2016,
      rating: 4.6,
      privatePrice: 2700,
      groupPrice: 1350,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "B1 ve A2 seviyelerinde ders veriyor.",
      specialties: ["A2-1", "A2-2", "B1-1"]
    },
    {
      slug: "muge-suer",
      name: "Müge Süer",
      since: 2015,
      rating: 4.7,
      privatePrice: 2750,
      groupPrice: 1375,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "B1 ve B2 seviyelerinde eğitmen.",
      specialties: ["B1-1", "B1-2", "B2-1"]
    },
    {
      slug: "kudret-sayar",
      name: "Kudret Sayar",
      since: 2013,
      rating: 4.9,
      privatePrice: 3000,
      groupPrice: 1500,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "B1, B2 ve konuşma pratiğinde uzman.",
      specialties: ["B1-1", "B1-2", "B2-1", "B2-2", "Konuşma Pratiği"]
    },
    {
      slug: "onder-ozdil",
      name: "Önder Özdil",
      since: 2016,
      rating: 4.6,
      privatePrice: 2650,
      groupPrice: 1325,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "B1 ve konuşma pratiği dersleri.",
      specialties: ["B1-1", "B1-2", "Konuşma Pratiği"]
    },
    {
      slug: "atilla-poyraz",
      name: "Atilla Poyraz",
      since: 2016,
      rating: 4.6,
      privatePrice: 2700,
      groupPrice: 1350,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "B1 ve A2 seviyeleri.",
      specialties: ["A2-1", "A2-2", "B1-1"]
    },
    {
      slug: "ruhsar-dincer",
      name: "Ruhsar Dinçer",
      since: 2015,
      rating: 4.7,
      privatePrice: 2750,
      groupPrice: 1375,
      corporate: false,
      online: true,
      location: "Ankara",
      bio: "Ankara'da B1 ve konuşma pratiği.",
      specialties: ["B1-1", "B1-2", "Konuşma Pratiği"]
    },
    {
      slug: "figen-unal",
      name: "Figen Ünal",
      since: 2017,
      rating: 4.5,
      privatePrice: 2600,
      groupPrice: 1300,
      corporate: false,
      online: true,
      location: "Bursa",
      bio: "Bursa'da B1 ve A2 seviyeleri.",
      specialties: ["A2-1", "A2-2", "B1-1"]
    }
  ],
  description: "B1 seviyesi Almanca, orta seviyede dil bilgisi ve günlük konuşma becerilerini geliştirir. B1-1 ve B1-2 alt seviyelerini kapsar.",
  whyTake: "Almancayı akıcı bir şekilde konuşmaya başlamak için.",
  employmentAreas: "Müşteri temsilciliği, satış, yurt dışı eğitim.",
  requirements: "A2 seviyesini tamamlamış olmak."
},
{
  slug: "b2-seviyesi-almanca",
  title: "B2 Seviyesi Almanca (B2-1 / B2-2) Orta-İleri Seviye",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Almanca > B2 Orta-İleri",
  image: "/images/almanca.jpg",
  instructors: [
    {
      slug: "yekta-ozsan",
      name: "Yekta Özsan",
      since: 2013,
      rating: 4.9,
      privatePrice: 3400,
      groupPrice: 1700,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "B2, C1 ve konuşma pratiğinde uzman.",
      specialties: ["B2-1", "B2-2", "C1-1", "Konuşma Pratiği"]
    },
    {
      slug: "muge-suer",
      name: "Müge Süer",
      since: 2015,
      rating: 4.7,
      privatePrice: 3200,
      groupPrice: 1600,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "B2 ve B1 seviyelerinde eğitmen.",
      specialties: ["B1-1", "B1-2", "B2-1"]
    },
    {
      slug: "kudret-sayar",
      name: "Kudret Sayar",
      since: 2013,
      rating: 4.9,
      privatePrice: 3500,
      groupPrice: 1750,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "B2, B1 ve konuşma pratiği.",
      specialties: ["B1-1", "B1-2", "B2-1", "B2-2", "Konuşma Pratiği"]
    },
    {
      slug: "sema-kabak",
      name: "Sema Kabak",
      since: 2014,
      rating: 4.8,
      privatePrice: 3300,
      groupPrice: 1650,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "B2 ve C1 seviyelerinde ders veriyor.",
      specialties: ["B2-1", "B2-2", "C1-1"]
    }
  ],
  description: "B2 seviyesi Almanca, orta-ileri düzeyde dil bilgisi ve akıcı konuşma becerileri kazandırır. B2-1 ve B2-2 alt seviyelerini kapsar.",
  whyTake: "Akademik ve profesyonel Almanca için gereklidir.",
  employmentAreas: "İş Almancası, uluslararası şirketler, yüksek lisans.",
  requirements: "B1 seviyesini tamamlamış olmak."
},
{
  slug: "c1-seviyesi-almanca",
  title: "C1 Seviyesi Almanca (C1-1 / C1-2) İleri Seviye",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Almanca > C1 İleri",
  image: "/images/almanca.jpg",
  instructors: [
    {
      slug: "fahri-coskun",
      name: "Fahri Coşkun",
      since: 2012,
      rating: 5.0,
      privatePrice: 4000,
      groupPrice: 2000,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "C1 ve C2 seviyelerinde uzman, akademik Almanca.",
      specialties: ["C1-1", "C1-2", "C2-1"]
    },
    {
      slug: "yekta-ozsan",
      name: "Yekta Özsan",
      since: 2013,
      rating: 4.9,
      privatePrice: 3900,
      groupPrice: 1950,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "C1, B2 ve konuşma pratiği.",
      specialties: ["B2-1", "B2-2", "C1-1", "Konuşma Pratiği"]
    },
    {
      slug: "jale-evrim",
      name: "Jale Evrim",
      since: 2012,
      rating: 5.0,
      privatePrice: 4200,
      groupPrice: 2100,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "C1 ve C2 seviyelerinde uzman.",
      specialties: ["C1-1", "C1-2", "C2-1"]
    },
    {
      slug: "necla-berksoy",
      name: "Necla Berksoy",
      since: 2011,
      rating: 5.0,
      privatePrice: 4300,
      groupPrice: 2150,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "C1 ve C2 seviyelerinde deneyimli.",
      specialties: ["C1-1", "C1-2", "C2-1", "C2-2"]
    },
    {
      slug: "sema-kabak",
      name: "Sema Kabak",
      since: 2014,
      rating: 4.8,
      privatePrice: 3800,
      groupPrice: 1900,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "C1 ve B2 seviyeleri.",
      specialties: ["B2-1", "B2-2", "C1-1"]
    },
    {
      slug: "tolga-ozkok",
      name: "Tolga Özkök",
      since: 2013,
      rating: 4.9,
      privatePrice: 4100,
      groupPrice: 2050,
      corporate: true,
      online: true,
      location: "İzmir",
      bio: "İzmir'de C1 ve C2 seviyeleri.",
      specialties: ["C1-1", "C1-2", "C2-1"]
    }
  ],
  description: "C1 seviyesi Almanca, ileri düzeyde dil bilgisi, akademik yazma ve konuşma becerileri kazandırır. C1-1 ve C1-2 alt seviyelerini kapsar.",
  whyTake: "Akademik kariyer ve profesyonel Almanca için gereklidir.",
  employmentAreas: "Akademisyenlik, yöneticilik, çevirmenlik.",
  requirements: "B2 seviyesini tamamlamış olmak."
},
{
  slug: "c2-seviyesi-almanca",
  title: "C2 Seviyesi Almanca (C2-1 / C2-2) Profesyonel Seviye",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Almanca > C2 Profesyonel",
  image: "/images/almanca.jpg",
  instructors: [
    {
      slug: "fahri-coskun",
      name: "Fahri Coşkun",
      since: 2012,
      rating: 5.0,
      privatePrice: 5000,
      groupPrice: 2500,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "C2 seviyesinde uzman, akademik Almanca.",
      specialties: ["C1-1", "C1-2", "C2-1"]
    },
    {
      slug: "tanju-cuce",
      name: "Tanju Cüce",
      since: 2013,
      rating: 4.9,
      privatePrice: 4800,
      groupPrice: 2400,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "C2 seviyesinde ders veriyor.",
      specialties: ["C2-1", "C2-2"]
    },
    {
      slug: "jale-evrim",
      name: "Jale Evrim",
      since: 2012,
      rating: 5.0,
      privatePrice: 5200,
      groupPrice: 2600,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "C2 ve C1 seviyelerinde uzman.",
      specialties: ["C1-1", "C1-2", "C2-1"]
    },
    {
      slug: "necla-berksoy",
      name: "Necla Berksoy",
      since: 2011,
      rating: 5.0,
      privatePrice: 5500,
      groupPrice: 2750,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "C2 seviyesinde deneyimli.",
      specialties: ["C1-1", "C1-2", "C2-1", "C2-2"]
    },
    {
      slug: "tolga-ozkok",
      name: "Tolga Özkök",
      since: 2013,
      rating: 4.9,
      privatePrice: 5000,
      groupPrice: 2500,
      corporate: true,
      online: true,
      location: "İzmir",
      bio: "İzmir'de C2 ve C1 seviyeleri.",
      specialties: ["C1-1", "C1-2", "C2-1"]
    }
  ],
  description: "C2 seviyesi Almanca, anadil seviyesinde akıcılık, akademik yazma ve ileri düzey iletişim becerileri kazandırır. C2-1 ve C2-2 alt seviyelerini kapsar.",
  whyTake: "Anadil seviyesinde Almanca için son adım.",
  employmentAreas: "Akademisyenlik, üst düzey yöneticilik, çevirmenlik.",
  requirements: "C1 seviyesini tamamlamış olmak."
},
{
  slug: "almanca-konusma-pratigi",
  title: "Almanca Konuşma Pratiği",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Almanca > Konuşma Pratiği",
  image: "/images/almanca.jpg",
  instructors: [
    {
      slug: "gulseren-tuzun",
      name: "Gülseren Tüzün",
      since: 2014,
      rating: 4.8,
      privatePrice: 2800,
      groupPrice: 1400,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "Konuşma pratiğinde uzman, akıcılık kazandırma.",
      specialties: ["B1-1", "B1-2", "Konuşma Pratiği"]
    },
    {
      slug: "yekta-ozsan",
      name: "Yekta Özsan",
      since: 2013,
      rating: 4.9,
      privatePrice: 3000,
      groupPrice: 1500,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "Konuşma pratiği ve ileri seviye dersler.",
      specialties: ["B2-1", "B2-2", "C1-1", "Konuşma Pratiği"]
    },
    {
      slug: "irfan-basaran",
      name: "İrfan Başaran",
      since: 2015,
      rating: 4.5,
      privatePrice: 2500,
      groupPrice: 1250,
      corporate: false,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "Konuşma pratiği ve A2 seviyeleri.",
      specialties: ["A2-1", "A2-2", "Konuşma Pratiği"]
    },
    
    {
      slug: "onder-ozdil",
      name: "Önder Özdil",
      since: 2016,
      rating: 4.6,
      privatePrice: 2700,
      groupPrice: 1350,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "Konuşma pratiği ve B1 seviyeleri.",
      specialties: ["B1-1", "B1-2", "Konuşma Pratiği"]
    },
    {
      slug: "ruhsar-dincer",
      name: "Ruhsar Dinçer",
      since: 2015,
      rating: 4.7,
      privatePrice: 2800,
      groupPrice: 1400,
      corporate: false,
      online: true,
      location: "Ankara",
      bio: "Ankara'da konuşma pratiği ve B1 seviyeleri.",
      specialties: ["B1-1", "B1-2", "Konuşma Pratiği"]
    }
  ],
  description: "Almanca konuşma pratiği dersleri, akıcılık kazanmak ve günlük konuşmalarda kendinizi rahat ifade etmek için tasarlanmıştır.",
  whyTake: "Konuşma becerinizi geliştirerek Almancayı aktif olarak kullanın.",
  employmentAreas: "Her seviyede Almanca gerektiren işler.",
  requirements: "En az A2 seviyesinde Almanca bilgisi önerilir."
},

// ===== DİĞER DİLLER =====
// Her dil için tek bir kurs, içinde tüm eğitmenler listelenecek. Fiyatlar 1500-2500 arası.
{
  slug: "arapca-dersi",
  title: "Arapça Dersi",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Arapça",
  image: "/images/arapca.jpg",
  instructors: [
    {
      slug: "sezgin-erdogan",
      name: "Sezgin Erdoğan",
      since: 2015,
      rating: 4.7,
      privatePrice: 1800,
      groupPrice: 900,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "Arapça eğitmeni, 8 yıllık deneyim.",
      specialties: ["Arapça"]
    },
    {
      slug: "nebahat-sumer",
      name: "Nebahat Sümer",
      since: 2016,
      rating: 4.6,
      privatePrice: 1700,
      groupPrice: 850,
      corporate: false,
      online: true,
      location: "Konya",
      bio: "Konya'da Arapça dersleri.",
      specialties: ["Arapça"]
    }
  ],
  description: "Arapça dersleri, temelden ileri seviyeye kadar her seviyede özel ders imkanı.",
  whyTake: "Arapça öğrenerek yeni kültürler keşfedin ve iş fırsatlarınızı artırın.",
  employmentAreas: "Tercümanlık, uluslararası ilişkiler, eğitim.",
  requirements: "Hiçbir ön koşul yoktur."
},
{
  slug: "cince-dersi",
  title: "Çince Dersi",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Çince",
  image: "/images/cince.jpg",
  instructors: [
    {
      slug: "gokhan-ozgur",
      name: "Gökhan Özgür",
      since: 2014,
      rating: 4.8,
      privatePrice: 2000,
      groupPrice: 1000,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "Çince eğitmeni, 9 yıllık deneyim.",
      specialties: ["Çince"]
    },
    {
      slug: "perihan-dilmen",
      name: "Perihan Dilmen",
      since: 2017,
      rating: 4.5,
      privatePrice: 1800,
      groupPrice: 900,
      corporate: false,
      online: true,
      location: "Ankara",
      bio: "Ankara'da Çince dersleri.",
      specialties: ["Çince"]
    }
  ],
  description: "Çince dersleri, temelden ileri seviyeye kadar her seviyede özel ders imkanı.",
  whyTake: "Dünyanın en çok konuşulan dilini öğrenerek küresel fırsatları yakalayın.",
  employmentAreas: "Uluslararası ticaret, tercümanlık, turizm.",
  requirements: "Hiçbir ön koşul yoktur."
},
{
  slug: "farsca-dersi",
  title: "Farsça Dersi",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Farsça",
  image: "/images/farsca.jpg",
  instructors: [
    {
      slug: "atif-yonel",
      name: "Atıf Yönel",
      since: 2015,
      rating: 4.7,
      privatePrice: 1900,
      groupPrice: 950,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "Farsça eğitmeni, 8 yıllık deneyim.",
      specialties: ["Farsça"]
    },
    {
      slug: "guzin-ilhan",
      name: "Güzin İlhan",
      since: 2016,
      rating: 4.6,
      privatePrice: 1800,
      groupPrice: 900,
      corporate: false,
      online: true,
      location: "Kayseri",
      bio: "Kayseri'de Farsça dersleri.",
      specialties: ["Farsça"]
    }
  ],
  description: "Farsça dersleri, temelden ileri seviyeye kadar her seviyede özel ders imkanı.",
  whyTake: "Zengin Fars edebiyatını ve kültürünü keşfedin.",
  employmentAreas: "Akademik çalışmalar, tercümanlık, turizm.",
  requirements: "Hiçbir ön koşul yoktur."
},
{
  slug: "fransizca-dersi",
  title: "Fransızca Dersi",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Fransızca",
  image: "/images/fransizca.jpg",
  instructors: [
    {
      slug: "yalcin-gurses",
      name: "Yalçın Gürses",
      since: 2013,
      rating: 4.9,
      privatePrice: 2200,
      groupPrice: 1100,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "Fransızca eğitmeni, 10 yıllık deneyim.",
      specialties: ["Fransızca"]
    },
    {
      slug: "sermin-yar",
      name: "Şermin Yar",
      since: 2016,
      rating: 4.6,
      privatePrice: 2000,
      groupPrice: 1000,
      corporate: false,
      online: true,
      location: "İzmir",
      bio: "İzmir'de Fransızca dersleri.",
      specialties: ["Fransızca"]
    }
  ],
  description: "Fransızca dersleri, temelden ileri seviyeye kadar her seviyede özel ders imkanı.",
  whyTake: "Aşkın ve diplomasinin dilini öğrenin.",
  employmentAreas: "Diplomasi, turizm, eğitim.",
  requirements: "Hiçbir ön koşul yoktur."
},
{
  slug: "hintce-dersi",
  title: "Hintçe Dersi",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Hintçe",
  image: "/images/hintce.jpg",
  instructors: [
    {
      slug: "cevat-kelleci",
      name: "Cevat Kelleci",
      since: 2015,
      rating: 4.7,
      privatePrice: 1900,
      groupPrice: 950,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "Hintçe eğitmeni, 8 yıllık deneyim.",
      specialties: ["Hintçe"]
    },
    {
      slug: "nese-karabocek",
      name: "Neşe Karaböcek",
      since: 2017,
      rating: 4.5,
      privatePrice: 1800,
      groupPrice: 900,
      corporate: false,
      online: true,
      location: "Antalya",
      bio: "Antalya'da Hintçe dersleri.",
      specialties: ["Hintçe"]
    }
  ],
  description: "Hintçe dersleri, temelden ileri seviyeye kadar her seviyede özel ders imkanı.",
  whyTake: "Bollywood filmlerini anlamak ve Hindistan'ın zengin kültürünü keşfetmek için.",
  employmentAreas: "Turizm, tercümanlık, kültürel çalışmalar.",
  requirements: "Hiçbir ön koşul yoktur."
},
{
  slug: "ispanyolca-dersi",
  title: "İspanyolca Dersi",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > İspanyolca",
  image: "/images/ispanyolca.jpg",
  instructors: [
    {
      slug: "hakki-devrim",
      name: "Hakkı Devrim",
      since: 2014,
      rating: 4.8,
      privatePrice: 2100,
      groupPrice: 1050,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "İspanyolca eğitmeni, 9 yıllık deneyim.",
      specialties: ["İspanyolca"]
    },
    {
      slug: "munir-ozhan",
      name: "Münir Özhan",
      since: 2016,
      rating: 4.6,
      privatePrice: 2000,
      groupPrice: 1000,
      corporate: false,
      online: true,
      location: "Bursa",
      bio: "Bursa'da İspanyolca dersleri.",
      specialties: ["İspanyolca"]
    }
  ],
  description: "İspanyolca dersleri, temelden ileri seviyeye kadar her seviyede özel ders imkanı.",
  whyTake: "Dünyada en çok konuşulan ikinci dili öğrenin.",
  employmentAreas: "Uluslararası ticaret, turizm, eğitim.",
  requirements: "Hiçbir ön koşul yoktur."
},
{
  slug: "italyanca-dersi",
  title: "İtalyanca Dersi",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > İtalyanca",
  image: "/images/italyanca.jpg",
  instructors: [
    {
      slug: "suna-pek",
      name: "Suna Pek",
      since: 2015,
      rating: 4.7,
      privatePrice: 2000,
      groupPrice: 1000,
      corporate: true,
      online: true,
      location: "İstanbul Avrupa Yakası",
      bio: "İtalyanca eğitmeni, 8 yıllık deneyim.",
      specialties: ["İtalyanca"]
    },
    {
      slug: "erol-gunaydin",
      name: "Erol Günaydın",
      since: 2016,
      rating: 4.6,
      privatePrice: 1900,
      groupPrice: 950,
      corporate: false,
      online: true,
      location: "Eskişehir",
      bio: "Eskişehir'de İtalyanca dersleri.",
      specialties: ["İtalyanca"]
    }
  ],
  description: "İtalyanca dersleri, temelden ileri seviyeye kadar her seviyede özel ders imkanı.",
  whyTake: "Sanatın, müziğin ve mutfağın dilini öğrenin.",
  employmentAreas: "Sanat tarihi, turizm, gastronomi.",
  requirements: "Hiçbir ön koşul yoktur."
},
{
  slug: "japonca-dersi",
  title: "Japonca Dersi",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Japonca",
  image: "/images/japonca.jpg",
  instructors: [
    {
      slug: "ihsan-yuce",
      name: "İhsan Yüce",
      since: 2014,
      rating: 4.8,
      privatePrice: 2200,
      groupPrice: 1100,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "Japonca eğitmeni, 9 yıllık deneyim.",
      specialties: ["Japonca"]
    },
    {
      slug: "gonul-ulku",
      name: "Gönül Ülkü",
      since: 2017,
      rating: 4.5,
      privatePrice: 2000,
      groupPrice: 1000,
      corporate: false,
      online: true,
      location: "Trabzon",
      bio: "Trabzon'da Japonca dersleri.",
      specialties: ["Japonca"]
    }
  ],
  description: "Japonca dersleri, temelden ileri seviyeye kadar her seviyede özel ders imkanı.",
  whyTake: "Japon kültürüne ve teknolojisine ilgi duyanlar için.",
  employmentAreas: "Teknoloji, akademik çalışmalar, çeviri.",
  requirements: "Hiçbir ön koşul yoktur."
},
{
  slug: "kurtce-dersi",
  title: "Kürtçe Dersi",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Kürtçe",
  image: "/images/kurtce.jpg",
  instructors: [
    {
      slug: "nubar-terzi",
      name: "Nubar Terzi",
      since: 2015,
      rating: 4.7,
      privatePrice: 1800,
      groupPrice: 900,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "Kürtçe eğitmeni, 8 yıllık deneyim.",
      specialties: ["Kürtçe"]
    },
    {
      slug: "muazzez-kurtoglu",
      name: "Muazzez Kurtoğlu",
      since: 2016,
      rating: 4.6,
      privatePrice: 1700,
      groupPrice: 850,
      corporate: false,
      online: true,
      location: "Diyarbakır",
      bio: "Diyarbakır'da Kürtçe dersleri.",
      specialties: ["Kürtçe"]
    }
  ],
  description: "Kürtçe dersleri, temelden ileri seviyeye kadar her seviyede özel ders imkanı.",
  whyTake: "Kürtçe öğrenerek bölgesel iletişim ve kültürel bağlarınızı güçlendirin.",
  employmentAreas: "Yerel yönetimler, eğitim, medya.",
  requirements: "Hiçbir ön koşul yoktur."
},
{
  slug: "macarca-dersi",
  title: "Macarca Dersi",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Macarca",
  image: "/images/macarca.jpg",
  instructors: [
    {
      slug: "sami-hazinses",
      name: "Sami Hazinses",
      since: 2015,
      rating: 4.7,
      privatePrice: 1900,
      groupPrice: 950,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "Macarca eğitmeni, 8 yıllık deneyim.",
      specialties: ["Macarca"]
    },
    {
      slug: "feridun-karakaya",
      name: "Feridun Karakaya",
      since: 2016,
      rating: 4.6,
      privatePrice: 1800,
      groupPrice: 900,
      corporate: false,
      online: true,
      location: "Adana",
      bio: "Adana'da Macarca dersleri.",
      specialties: ["Macarca"]
    }
  ],
  description: "Macarca dersleri, temelden ileri seviyeye kadar her seviyede özel ders imkanı.",
  whyTake: "Avrupa'nın en ilginç dillerinden birini öğrenin.",
  employmentAreas: "Akademik çalışmalar, turizm, tercümanlık.",
  requirements: "Hiçbir ön koşul yoktur."
},
{
  slug: "portekizce-dersi",
  title: "Portekizce Dersi",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Portekizce",
  image: "/images/portekizce.jpg",
  instructors: [
    {
      slug: "halis-kentmen",
      name: "Halis Kentmen",
      since: 2014,
      rating: 4.8,
      privatePrice: 2100,
      groupPrice: 1050,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "Portekizce eğitmeni, 9 yıllık deneyim.",
      specialties: ["Portekizce"]
    },
    {
      slug: "vahi-oz",
      name: "Vahi Öz",
      since: 2016,
      rating: 4.6,
      privatePrice: 2000,
      groupPrice: 1000,
      corporate: false,
      online: true,
      location: "Samsun",
      bio: "Samsun'da Portekizce dersleri.",
      specialties: ["Portekizce"]
    }
  ],
  description: "Portekizce dersleri, temelden ileri seviyeye kadar her seviyede özel ders imkanı.",
  whyTake: "Brezilya ve Portekiz'in kapılarını aralayın.",
  employmentAreas: "Uluslararası ticaret, turizm, eğitim.",
  requirements: "Hiçbir ön koşul yoktur."
},
{
  slug: "rusca-dersi",
  title: "Rusça Dersi",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Rusça",
  image: "/images/rusca.jpg",
  instructors: [
    {
      slug: "renan-fosforoglu",
      name: "Renan Fosforoğlu",
      since: 2013,
      rating: 4.9,
      privatePrice: 2300,
      groupPrice: 1150,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "Rusça eğitmeni, 10 yıllık deneyim.",
      specialties: ["Rusça"]
    },
    {
      slug: "necdet-tosun",
      name: "Necdet Tosun",
      since: 2015,
      rating: 4.7,
      privatePrice: 2100,
      groupPrice: 1050,
      corporate: false,
      online: true,
      location: "Mersin",
      bio: "Mersin'de Rusça dersleri.",
      specialties: ["Rusça"]
    }
  ],
  description: "Rusça dersleri, temelden ileri seviyeye kadar her seviyede özel ders imkanı.",
  whyTake: "Geniş coğrafyada konuşulan Rusçayı öğrenin.",
  employmentAreas: "Enerji, turizm, uluslararası ilişkiler.",
  requirements: "Hiçbir ön koşul yoktur."
},
{
  slug: "yabancilara-turkce-dersi",
  title: "Yabancılara Türkçe Dersi",
  category: "Dil Eğitimi",
  breadcrumb: "Dil Eğitimi > Yabancılara Türkçe",
  image: "/images/turkce.jpg",
  instructors: [
    {
      slug: "mualla-surer",
      name: "Mualla Sürer",
      since: 2014,
      rating: 4.8,
      privatePrice: 2000,
      groupPrice: 1000,
      corporate: true,
      online: true,
      location: "İstanbul Anadolu Yakası",
      bio: "Yabancılara Türkçe eğitmeni, 9 yıllık deneyim.",
      specialties: ["Yabancılara Türkçe"]
    },
    {
      slug: "aleya-ronay",
      name: "Aleyna Ronay",
      since: 2016,
      rating: 4.6,
      privatePrice: 1900,
      groupPrice: 950,
      corporate: false,
      online: true,
      location: "Gaziantep",
      bio: "Gaziantep'te yabancılara Türkçe dersleri.",
      specialties: ["Yabancılara Türkçe"]
    }
  ],
  description: "Yabancılara Türkçe dersleri, temelden ileri seviyeye kadar her seviyede özel ders imkanı.",
  whyTake: "Türkçeyi öğrenerek Türkiye'de eğitim ve iş fırsatları yakalayın.",
  employmentAreas: "Eğitim, turizm, uluslararası şirketler.",
  requirements: "Hiçbir ön koşul yoktur."
}
];