name = "istanbul-egitim-merkezi"
compatibility_date = "2024-03-20"
pages_build_output_dir = "dist"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "istanbul-egitim-db"
database_id = "4838af92-cbdd-4545-bd41-d63db336b877"

# R2 Bucket Binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "istanbul-egitim-media"
